### ISSUE TITLE
What about Signin the package in the pipeline

### ISSUE THREAD

**Issue by SibeeshVenu** [damienaicheh/UWP-Pipeline#1]
Hi, thanks a lot for this [article ](https://damienaicheh.github.io/uwp/azure/devops/appcenter/2019/09/24/build-sign-and-deploy-your-uwp-application-using-azure-devops-and-appcenter-en.html). I followed it and my build and release to the AppCenter works fine, however when I try to install the application, I get the error as "Ask the app developer for a new app package. This one isn't signed with a trusted certificate (0x800B0100)". Are there any additional steps I need to add apart [from this](https://github.com/damienaicheh/UWP-Pipeline/blob/master/azure-pipelines.yml) ? Awaiting your response, thanks in advance.

**Comment by damienaicheh** [comment]
Hi, there is no additional steps to get it works, every tutorial is fully complete. If you create your PFX certificate using the official documentation as I mentionned in the tutorial, it should be good. Here is some ideas that you can try : 
- Install it using the install.ps1 generated as administrator in a Powershell, it will ask you to install the PFX before installing your application.
- I don't know what kind of environment you have but what the error said, is that your certificate is not trusted so maybe your operating system does not reconized it and you need to install it manually in your machine before in the trusted certificates.
- If you can, try to deploy it in another machine and see if you get the same problem or not.
Hope thes ideas will be helpful for you, I know cerfiticates can be difficult to manage. Good luck!

**Comment by SibeeshVenu** [comment]
Thanks a lot for the response. I created the certificate as per [this documentation](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing). And do I need to follow [this step too](https://docs.microsoft.com/en-us/windows/msix/package/sign-app-package-using-signtool)? I am trying to install the application in Windows 10 X64, and I don't see any powershell file from the appxbuild file I downloaded from the App Center. 

There is no Digital Signature option when I right click on the appxbundle file, so I guess the signin is not been done.

![image](https://user-images.githubusercontent.com/4262147/68073351-9268c080-fd8f-11e9-8ffe-b6866081420c.png)


I am a newbie in UWP development, so I am actually not sure how to move on. I really appreciate your help here. Thanks in advance.

**Comment by damienaicheh** [comment]
Ok I see, first you don't need to follow the second link about using signtool because it's already done by your azure jobs. 
If you want to see which certificate is applied to your appbundle it's in the Security tab in your screenshot. You will find the name of the certificate and his validity.
In my tutorial I export to Appcenter a zip file that contains the appbundle, there certificate, and other files depending on your OS configuration. You told me that you just download the appbundle. So I think you missed some files. Try to export the entire zip as I did and you will have all the files you need. It looks like it doesn't have the certificate to install with it to be able to work correctly.

**Comment by SibeeshVenu** [comment]
Thanks a lot for the response. I see that the certificates are being generated in the artifacts. 

![image](https://user-images.githubusercontent.com/4262147/68073727-651e1180-fd93-11e9-8de4-af9a9c6b7ee7.png)

As you said it seems like the problem is with my App Center Release Task it seems. Can you please help me to change it to the right command. Below is my current task.

```
- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'release to app center'
    appSlug: '$(appSlug)'
    appFile: '$(build.artifactstagingdirectory)\AppxPackages\Player_$(Build.BuildNumber)_x86_x64_bundle.appxupload'
    releaseNotesOption: 'input'
    releaseNotesInput: 'New release!'
    destinationType: 'groups'
    distributionGroupId: '$(distributionGroupId)'
```
And you are also uploading the appx bundle file right, not the zip as [per this step](https://github.com/damienaicheh/UWP-Pipeline/blob/master/azure-pipelines.yml#L79). If I use the command as you use in your article saying that multiple appxbuldle found in the pipeline. 

`appFile: '$(build.artifactstagingdirectory)\AppxPackages\*.appxupload'`

I am a bit confused here. Any help is really appreciated.

**Comment by damienaicheh** [comment]
Oh yes you are right. The zip file was another test that I did not published. Just to see if you are creating everything correctly, just downlaod manually your artifacts and install your app. If it's working fine If  just add an ArchiveFiles@2 task to generate a zip to export your entire AppxPackages into Appcenter.

**Comment by SibeeshVenu** [comment]
Thanks a lot for the response. Finally I was able to do that.

**Comment by SibeeshVenu** [comment]
I just [written an article with all the details I had](
https://medium.com/@sibeeshvenu/uwp-application-singin-release-distribute-deploy-with-azure-devops-pipeline-118580bd4d75?sk=a9909f32626230c9942778f2f135742b) :). I really appreciate your feedback!.

**Comment by damienaicheh** [comment]
It's looking good! Just change the title from Singing to Signing and you are good to go!
